# Generated by Django 5.0.4 on 2024-05-03 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testingApp', '0003_delete_koti_remove_user_nick_name_user_nickname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20)),
                ('employee_name', models.CharField(max_length=100)),
                ('department_id', models.CharField(max_length=20)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('department_name', models.CharField(max_length=100)),
                ('department_location', models.CharField(max_length=100)),
            ],
        ),
    ]
